config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  get "users/account", to: "users#account"
  get "users/show", to: "users#show"
  get "users/show/edit", to: "users#edit"
  resources :users, only: %i[show edit update]
  root "home#index"
  get "rooms/own", to: "rooms#index"
  get "search", to: "rooms#search", as: "search_rooms"
  resources :rooms
  resources :bookings do
    collection { post "confirm" }
  end
  post "bookings/:id" => "bookings#index"
  get "bookings/index", to: "bookings#index"
end

app/views/layouts/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <%= link_to home_index_path do %>
        <%= image_tag 'logo.png', alt:"サイトロゴ", class:"footer-logo" %>
    <% end %>
  </div>
</footer>

app/views/layouts/shared/_logged_in_header.html.erb
<header>
  <nav class="navbar Navbar">
    <div class="container-fluid">
      <%= link_to home_index_path do %>
        <%= image_tag 'logo.png', alt:"サイトロゴ", class:"navbar-logo" %>
      <% end %> 
      <div class="dropdown">
        <a class="d-flex align-items-center NavProfile dropdown-toggle" href="#" id="dropdown-button" data-bs-toggle="dropdown" aria-expanded="false">
          <div class="userinformation">
            <% if current_user.image? %>
              <%= image_tag current_user.image.url %>
            <% else %>
              <%= image_tag ("defaulticon.png") %>
            <% end %>
            <span><%= current_user.name %></span>
          </div> 
        </a>   
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li class="dropdown-item"><%= link_to "施設を新規登録", new_room_path %></li>
          <hr class="dropdown-hr">
          <li class="dropdown-item"><%= link_to "予約済み一覧", bookings_path %></li>
          <li class="dropdown-item middle"><%= link_to "登録済み一覧", rooms_own_path %></li>
          <li class="dropdown-item"><%= link_to "アカウント設定", users_account_path %></li>
          <hr class="dropdown-hr">
          <li class="dropdown-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>  
    </div>
  </nav>
</header>

app/views/layouts/shared/_logged_out_header.html.erb
<header>
  <nav class="navbar">
    <div class="container-fluid">
      <%= link_to home_index_path do %>
        <%= image_tag 'logo.png', alt:"サイトロゴ", class:"navbar-logo" %>
      <% end %>  
      <div class="navbar-link">
        <%= link_to 'ログイン', new_user_session_path, class:"sign-in-button" %>
        <%= link_to '新規登録', new_user_registration_path, class:"sign-up-button" %>
      </div>
    </div>
  </nav>
</header> 