config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  get "users/account", to: "users#account"
  get "users/show", to: "users#show"
  get "users/show/edit", to: "users#edit"
  resources :users, only: %i[show edit update]
  root "home#index"
  get "rooms/own", to: "rooms#index"
  get "search", to: "rooms#search", as: "search_rooms"
  resources :rooms
  resources :bookings do
    collection { post "confirm" }
  end
  post "bookings/:id" => "bookings#index"
  get "bookings/index", to: "bookings#index"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :checkin_date, :checkout_date, :guest, presence: true
  validate :start_end_check

  def start_end_check
    if checkin_date == nil
      errors.add(:checkin_date, "開始日を入力してください")
    elsif checkout_date == nil
      errors.add(:checkout_date, "終了日を入力してください")
    elsif checkout_date < checkin_date
      errors.add(:checkout_date, "終了日は開始日よりも後の日付にしてください")
    end
  end
  def total_date
    duration = (checkout_date - checkin_date).to_i
  end
  def total_price
    total_date * guest * room.price
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @bookings = Booking.where(user_id: current_user.id).includes(:user)
  end

  def new
    @user = current_user
    @room = Room.find(params[:room_id])
    @booking = Booking.new
  end

  def create
    @user = User.find_by(params[:booking][:user_id])
    @room = Room.find(params[:booking][:room_id])
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to bookings_path
    else
      render template: "bookings/index"
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render template: "bookings/index"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def confirm
    @booking = Booking.new(booking_params)
    @user = current_user
    @room = Room.find(params[:booking][:room_id])
  end

  private

  def booking_params
    params.require(:booking).permit(
      :checkin_date,
      :checkout_date,
      :guest,
      :total_price,
      :total_date,
      :room_id,
      :user_id,
    )
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/confirm.html.erb
<%= header_links %>
<div class="ConfirmFormWrapper">
  <section class="ConfirmForm">
  <%= form_with model: @booking, local: true do |f| %>
    <h2>予約内容の確認</h2>
    <div class="BookingConfirm">
      <p class="BookingConfirmLabel">チェックイン</p>
      <p class="BookingConfirmValue"><%= @booking.checkin_date %></p>
    </div>
    <div class="BookingConfirm">
      <p class="BookingConfirmLabel">チェックアウト</p>
      <p class="BookingConfirmValue"><%= @booking.checkout_date %></p>
    </div>
    <div class="BookingConfirm">
      <p class="BookingConfirmLabel">日数</p>
      <p class="BookingConfirmValue"><%= @booking.total_date %></p>
    </div>
    <div class="BookingConfirm">
      <p class="BookingConfirmLabel">人数</p>
      <p class="BookingConfirmValue"><%= @booking.guest %></p>
    </div>
    <div class="BookingConfirm">
      <p class="BookingConfirmLabel">お支払い金額</p>
      <p class="BookingConfirmPrice">¥<%= number_with_delimiter(@booking.total_price) %></p>
    </div>
    <p class="BookingConfirmDescription">上記の内容で正しければ、「予約を確定」ボタンを押して下さい</p>
    <%= f.hidden_field :checkin_date, value: @booking.checkin_date %>
    <%= f.hidden_field :checkout_date, value: @booking.checkout_date %>
    <%= f.hidden_field :guest, value: @booking.guest %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.submit "予約を確定", class:"btn btn-submit" %>
    <%= link_to "キャンセル", request.referer, class: "btn btn-cancel" %>
  <% end %>
  </section>
</div>
<%= render 'layouts/shared/footer' %>

app/views/bookings/edit.html.erb
<%= header_links %>
<div class="EditBookingWrapper">
  <section class="EditBookingContainer">
    <h2>予約を編集する</h2>
    <div class="BookingDetails">
      <%= @booking.room.roomimage? ? image_tag(booking.room.roomimage.url) : image_tag("room.png") %>
      <div class="BookingDetailsHeader">
        <p><%= @booking.room.name %></p>
        <span>¥<%= number_with_delimiter(@booking.room.price) %>〜</span>
      </div>
      <span class="BookingDetailsAddress"><%= @booking.room.address %></span>
      <p class="BookingDetailsDescription"><%= @booking.room.description %></p>
    </div>
    <%= form_with model: @booking, local: true do |f| %>
    <div class="form-group">
      <%= f.label :checkin_date, "チェックイン", class:"form-label" %>
      <%= f.date_field :checkin_date, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :checkout_date, "チェックアウト", class:"form-label" %>
      <%= f.date_field :checkout_date, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :guest, "人数", class:"form-label" %>
      <%= f.number_field :guest, class:"form-control" %>
    </div>
    <div class="form-buttons">
      <%= f.submit "予約を編集する", class:"btn submit" %>
      <%= link_to "キャンセル", :back, class:"btn cancel" %>
    </div>
    <% end %>
  </section>
</div>
<%= render 'layouts/shared/footer' %>

app/views/bookings/index.html.erb
<%= header_links %>
<div class="BookingsContainer">
  <h2>予約済み一覧</h2>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th class="text-nowrap">合計料金</th>
          <th class="text-nowrap">チェックイン</th>
          <th class="text-nowrap">チェックアウト</th>
          <th class="text-nowrap">予約確定日時</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
        <tr>
          <td>
            <%= link_to room_path(booking.room) do%>
            <%= booking.room.roomimage? ? image_tag(booking.room.roomimage.url) : image_tag("room.png") %>
            <% end %>
          </td>
          <td>
            <%= link_to room_path(booking.room) do %>
            <p><%= booking.room.name %></p>
            <% end %>
          </td>
          <td>
            <p><%= booking.room.description %></p>
          </td>
          <td class="text-nowrap">
            <p>¥<%= number_with_delimiter(booking.total_price) %></p>
          </td>
          <td class="text-nowrap">
            <p><%= booking.checkin_date.strftime("%Y/%m/%d") %></p>
          </td>
          <td class="text-nowrap">
            <p><%= booking.checkout_date.strftime("%Y/%m/%d") %></p>
          </td>
          <td class="text-nowrap">
            <p><%= booking.created_at.strftime("%Y/%m/%d %H:%M") %></p>
          </td>
          <td>
                <div class="dropdown">
                  <div class="d-flex align-items-center justify-content-center" id="dropdown-button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= image_tag ("three-dot-menu.svg") %>
                  </div>
                  <ul class="dropdown-menu DropdownMenu" aria-labelledby="dropdown-button">
                    <li class="dropdown-item"><%= link_to "編集", edit_booking_path(booking) %></li>
                    <li class="dropdown-item danger"><%= link_to "削除",booking_path(booking), data: { turbo_method: :delete } %></li>
                  </ul>  
                </div>
              </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= render 'layouts/shared/footer' %>