config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  get "users/account", to: "users#account"
  get "users/show", to: "users#show"
  get "users/show/edit", to: "users#edit"
  resources :users, only: %i[show edit update]
  root "home#index"
  get "rooms/own", to: "rooms#index"
  get "search", to: "rooms#search", as: "search_rooms"
  resources :rooms
  resources :bookings do
    collection { post "confirm" }
  end
  post "bookings/:id" => "bookings#index"
  get "bookings/index", to: "bookings#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :bookings
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :introduction, length: { maximum: 300 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @user = current_user
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_show_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<%= header_links %>
<section class="UserSection">
  <h2>設定</h2>
  <div class="UserContainer">
    <ul class="NavList">
      <li class="NavListItem <%= 'active' if current_page?(users_account_path) %>">
        <%= link_to "アカウント", users_account_path, class:"NavListItemLink" %>
      </li>
      <li class="NavListItem">
        <%= link_to "プロフィール", users_show_path, class:"NavListItemLink" %>
      </li>
    </ul>
    <div class="AccountInformation">
      <div class="AccountHeader">
        <h3>アカウント</h3>
        <%= link_to "編集", edit_user_registration_path, class:"AccountEditLink" %>
      </div>
      <div class="AccountItem">
        <h4>メールアドレス</h4>
        <p><%= @user.email %></p>
      </div>
      <div class="AccountItem">
        <h4>パスワード</h4>
        <p>******</p>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/shared/footer' %>

app/views/users/edit.html.erb
<%= header_links %>
<section class="UserSection">
  <h2>設定</h2>
  <div class="UserContainer">
    <ul class="NavList">
      <li class="NavListItem">
        <%= link_to "アカウント", users_account_path, class:"NavListItemLink" %>
      </li>
      <li class="NavListItem <%= 'active' if current_page?(users_show_edit_path) %>">
        <%= link_to "プロフィール", users_show_path, class:"NavListItemLink" %>
      </li>
    </ul>
    <div class="AccountInformation">
      <div class="AccountHeader">
        <h3>プロフィール</h3>
        <%= link_to "編集", users_show_edit_path, class:"AccountEditLink" %>
      </div>
      <%= form_for @user, url: user_path(@user), method: :patch do |f| %>
      <div class="mb-4 form-group">
        <div class="label-text">
          <%= f.label :image, "アイコン画像", class: "form-label" %>
        </div>
        <div class="user-icon">
          <% if current_user.image? %>
            <%= image_tag current_user.image.url %>
          <% else %>
            <%= image_tag ("defaulticon.png") %>
          <% end %>
        </div>
        <div class="upload-form">
          <%= f.file_field :image, label: "画像をアップロード", class: 'form-control' %>
        </div>
      </div>
      <div class="mb-4 form-group">
        <div class="label-text">
          <%= f.label :name, "名前", class: "form-label" %>
        </div>
        <div class="input-form">
          <%= f.text_field :name, class: 'form-control', placeholder:"名前を入力" %>
        </div>
      </div>
      <div class="mb-4 form-group">
        <div class="label-text">
          <%= f.label :introcution, "自己紹介", class: "form-label" %>
        </div>
        <div class="input-form">
          <%= f.text_area :introduction, class: 'form-control', id:"form-introduction", placeholder:"自己紹介を入力" %>
        </div>
      </div>    
      <div class="form-buttons">
        <%= link_to "キャンセル", users_show_path, class:"btn btn-outline-secondary cancel " %>
        <%= f.submit "保存", class:"btn btn-primary submit " %>
      </div>
      <% end %>
    </div>
  </div>
</section>
<%= render 'layouts/shared/footer' %>

app/views/users/show.html.erb
<%= header_links %>
<section class="UserSection">
  <h2>設定</h2>
  <div class="UserContainer">
    <ul class="NavList">
      <li class="NavListItem">
        <%= link_to "アカウント", users_account_path, class:"NavListItemLink" %>
      </li>
      <li class="NavListItem <%= 'active' if current_page?(users_show_path) %>">
        <%= link_to "プロフィール", users_show_path, class:"NavListItemLink" %>
      </li>
    </ul>
    <div class="AccountInformation">
      <div class="AccountHeader">
        <h3>プロフィール</h3>
        <%= link_to "編集", users_show_edit_path, class:"AccountEditLink" %>
      </div>
      <div class="AccountItem">
        <h4>アイコン画像</h4>
        <% if current_user.image? %>
          <%= image_tag current_user.image.url %>
        <% else %>
          <%= image_tag ("defaulticon.png") %>
        <% end %>
      </div>
      <div class="AccountItem">
        <h4>名前</h4>
        <p><%= @user.name %></p>
      </div>
      <div class="AccountItem">
        <h4>自己紹介</h4>
        <p><%= @user.introduction %> </p>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/shared/footer' %>