config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  get "home/index"
  get "users/account", to: "users#account"
  get "users/show", to: "users#show"
  get "users/show/edit", to: "users#edit"
  resources :users, only: %i[show edit update]
  root "home#index"
  get "rooms/own", to: "rooms#index"
  get "search", to: "rooms#search", as: "search_rooms"
  resources :rooms
  resources :bookings do
    collection { post "confirm" }
  end
  post "bookings/:id" => "bookings#index"
  get "bookings/index", to: "bookings#index"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :bookings
  AREA_OPTIONS = %w[東京 大阪 京都 札幌]
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true, inclusion: { in: AREA_OPTIONS }
  mount_uploader :roomimage, RoomimageUploader
  scope :search, ->(query) { ransack(name_or_description_cont: query).result }
  def self.ransackable_attributes(auth_object = nil)
    %w[name address description price]
  end
  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = current_user.rooms
    @user = current_user
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @q = Room.ransack
    @booking = Booking.new
    @user = current_user
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      redirect_to room_path(@room.id)
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_own_path
  end

  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  private

  def room_params
    params
      .require(:room)
      .permit(:name, :description, :price, :address, :roomimage, :room_id)
      .merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<%= header_links %>
<div class="FormWrapper">
  <section class="FormContainer">
    <h2>施設情報の編集</h2>
    <%= form_with model: @room, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "施設名", class:"form-label" %>
      <%= f.text_field :name, class:"form-control", placeholder:"施設名を入力" %>
    </div>
    <div class="form-group">
      <%= f.label :description, "施設詳細", class:"form-label" %>
      <%= f.text_area :description, class:"form-control", placeholder:"施設詳細を入力", rows:"5" %>
    </div>
    <div class="form-group">
      <%= f.label :price, "料金", class:"form-label" %>
      <%= f.text_field :price, class:"form-control", placeholder:"一泊の料金を入力" %>
    </div>
    <div class="form-group">
      <%= f.label :address, "住所", class:"form-label" %>
      <%= f.text_field :address, class:"form-control", placeholder:"住所を入力" %>
    </div>
    <div class="form-group uploadarea">
      <%= f.label :roomimage, "施設画像", class:"form-label" %>
      <%= f.file_field :roomimage, label:"画像をアップロード", class:"form-control" %>
    </div>
    <div class="form-buttons">
      <%= f.submit "登録", class:"btn btn-primary submit" %>
      <%= link_to "キャンセル", rooms_own_path, class:"btn btn-outline-secondary cancel" %>
    </div>
    <% end %>
  </section>
</div>
<%= render 'layouts/shared/footer' %>

app/views/rooms/index.html.erb
<%= header_links %>
  <section class="OwnRoomsContainer">
    <h2>登録済みの部屋一覧</h2>
    <div class="table-responsive">
      <table class="table OwnRoomsTable">
        <thead>
          <tr>
            <th>画像</th>
            <th>施設名</th>
            <th>紹介文</th>
            <th>料金</th>
            <th>作成日</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @rooms.each do |room| %>
            <tr>
              <td>
                <%= link_to room_path(room) do %>
                <% if room.roomimage? %>
                  <%= image_tag room.roomimage.url %>
                <% else %>
                  <%= image_tag ("room.png") %>
                <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to room_path(room) do %>
                <p><%= room.name %></p>
                <% end %>
              </td>
              <td>
                <p><%= room.description %></p>
              </td>
              <td>
                <p><%= number_with_delimiter(room.price) %>円〜/日</p>
              </td>
              <td>
                <p><%= room.created_at.strftime("%Y/%m/%d")%></p>
              </td>
              <td>
                <div class="dropdown">
                  <div class="d-flex align-items-center justify-content-center" id="dropdown-button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= image_tag ("three-dot-menu.svg") %>
                  </div>
                  <ul class="dropdown-menu DropdownMenu" aria-labelledby="dropdown-button">
                    <li class="dropdown-item"><%= link_to "編集", edit_room_path(room) %></li>
                    <li class="dropdown-item danger"><%= link_to "削除", room_path(room), data: { turbo_method: :delete } %></li>
                  </ul>  
                </div>
              </td>
            </tr>
          <% end %>  
        </tbody>
      </table>
    </div>
  </section>
<%= render 'layouts/shared/footer' %>

app/views/rooms/new.html.erb
<%= header_links %>
<div class="FormWrapper">
  <section class="FormContainer">
    <h2>新規登録</h2>
    <%= form_with model: @room, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "施設名", class:"form-label" %>
      <%= f.text_field :name, class:"form-control", placeholder:"施設名を入力" %>
    </div>
    <div class="form-group">
      <%= f.label :description, "施設詳細", class:"form-label" %>
      <%= f.text_area :description, class:"form-control", placeholder:"施設詳細を入力", rows:"5" %>
    </div>
    <div class="form-group">
      <%= f.label :price, "料金", class:"form-label" %>
      <%= f.text_field :price, class:"form-control", placeholder:"一泊の料金を入力" %>
    </div>
    <div class="form-group">
      <%= f.label :address, "住所", class:"form-label" %>
      <%= f.text_field :address, class:"form-control", placeholder:"住所を入力" %>
    </div>
    <div class="form-group uploadarea">
      <%= f.label :roomimage, "施設画像", class:"upload-label" %>
      <%= f.file_field :roomimage, label:"画像をアップロード", class:"form-control" %>
    </div>
    <div class="form-buttons">
      <%= f.submit "登録", class:"btn btn-primary submit" %>
      <%= link_to "キャンセル", new_room_path, class:"btn btn-outline-secondary cancel" %>
    </div>
    <% end %>
  </section>
</div>
<%= render 'layouts/shared/footer' %>

app/views/rooms/search.html.erb
<%= header_links %>
<div class="SearchRoomsContainer">
  <div class="SearchRoomsForm">
    <%= search_form_for @q, url: search_rooms_path, method: :get do |f| %>
    <%= f.search_field :address_cont, class:"form-control", id:"search-form", placeholder:"エリアを入力" %>
    <%= f.search_field :name_or_description_cont, class:"form-control", id:"search-keyword", placeholder:"キーワードを入力" %>
    <%= f.submit "検索", id:"search-btn" %>
    <% end %>
  </div>
</div>
<div class="RoomsContainer">
<% if @rooms.empty? %>
  <p class="RoomsResult">0件が見つかりました。</p>
<% else %>
  <p class="RoomsResult"><%= @rooms.count %>件が見つかりました。</p>
  <ul class="RoomsList">
    <% @rooms.each do |room| %>
      <li class="Room">
        <div class="RoomImage">
          <% if room.roomimage? %>
            <%= image_tag room.roomimage.url %>
          <% else %>
            <%= image_tag ("room.png") %>
          <% end %>  
        </div>
        <div class="RoomWrapper">
          <p class="RoomName"><%= room.name %></p>
          <p class="RoomAddress"><%= room.address %></p>
          <p class="RoomDescription"><%= room.description %></p>
          <div class="RoomFooter">
            <p class="RoomPrice">¥<%= number_with_delimiter(room.price) %>〜</p>
            <%= link_to "詳細はこちら", room_path(room), class:"btn btn-danger" %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>
</div>
<%= render 'layouts/shared/footer' %>

app/views/rooms/show.html.erb
<%= header_links %>
<div class="SearchRoomsContainer">
  <div class="SearchRoomsForm">
    <%= search_form_for @q, url: search_rooms_path, method: :get do |f| %>
    <%= f.search_field :address_cont, class:"form-control", id:"search-form", placeholder:"エリアを入力" %>
    <%= f.search_field :name_or_description_cont, class:"form-control", id:"search-form", placeholder:"キーワードを入力" %>
    <%= f.submit "検索", id:"search-btn" %>
    <% end %>
  </div>
</div>
<div class ="RoomDetailsContainer">
  <div class="RoomDetailsHeader">
    <%= link_to "←戻る", request.referer %>
    <% if @room.user.id == current_user.id %>
      <%= link_to "編集", edit_room_path(@room) %>
    <% end %>
  </div>
  <div class="RoomDetails">
    <% if @room.roomimage? %>
      <%= image_tag @room.roomimage.url %>
    <% else %>
      <%= image_tag ("room.png") %>
    <% end %>
    <div class="RoomDetailsWrapper">
      <div class="RoomNameAndPrice">
        <p class="RoomName"><%= @room.name %></p>
        <p class="RoomPrice">¥<%= number_with_delimiter(@room.price) %>〜</p>
      </div>
      <p class="RoomAddress"><%= @room.address %></p>
      <p class="RoomDescription"><%= @room.description %></p>
      <div class="ReservationFormContainer">
        <%= form_with model: @booking, url: confirm_bookings_path, local: true do |f| %>
        <div class="ReservationForm">
          <div class="form-group">
            <%= f.label :checkin_date, "チェックイン" %>
            <%= f.date_field :checkin_date, id:"checkin_date", class:"form-control", placeholder:"---- / -- / --" %>
          </div>
          <div class="form-group">
            <%= f.label :checkout_date, "チェックアウト" %>
            <%= f.date_field :checkout_date, id:"checkout_date", class:"form-control", placeholder:"---- / -- / --" %>
          </div>
          <div class="form-group guest-count">
            <%= f.label :guest, "人数" %>
            <%= f.number_field :guest, class:"form-control" %>
          </div>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.hidden_field :user_id, value: @user.id %>
        </div> 
        <%= f.submit "予約する", class:"btn" %>   
        <% end %>           
      </div>
    </div>  
  </div>
</div>
<%= render 'layouts/shared/footer' %>